import ArrowDown from './arrowDown.svg'
import arrowMix from './arrows-mix.svg'
import Camera from './camera.svg'
import CreditCard from './credit-card.svg'
import Heart from './heart.svg'
import Image1 from './image1.png'
import Image2 from './image2.png'
import Image3 from './image3.png'
import Image4 from './image4.png'
import Item1 from './item1.jpg'
import Item2 from './item2.jpg'
import Item3 from './item3.jpg'
import Item4 from './item4.jpg'
import Item5 from './item5.jpg'
import Item6 from './item6.jpg'
import Item7 from './item7.jpg'
import Item8 from './item8.jpg'
import ItemGirl1 from './itemGirl1.png'
import ItemGirl2 from './itemGirl2.png'
import MaiGirl from './main-girl.png'
import MaiGirlNew from './main-girlNew.png'
import MaiImg from './main-img.png'
import Preview from './preview.jpg'
import Refund from './refund.svg'
import Search from './search.svg'
import Shipped from './shipped.svg'
import ShoppingBag from './shopping-bag1.png'
import ShoppingCart from './shopping-cart.svg'
import Support from './support.svg'
import TransparentGirl1 from './transparentGirl1.png'
import TransparentGirl2 from './transparentGirl2.png'

export {
    ArrowDown, arrowMix, Camera, CreditCard, Heart, Image1, Image2, Image3, Image4, Item1, Item2, Item3, Item4, Item5, Item6, Item7, Item8, ItemGirl1, ItemGirl2, MaiGirl, MaiGirlNew,
    MaiImg, Preview, Refund, Search, Shipped, ShoppingBag, ShoppingCart, Support, TransparentGirl1, TransparentGirl2
};